# MySQL Properties
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/online_job_portal?createDatabaseIfNotExist=true&useUnicode=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#enter the correct MySQL Password below
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Haryana@1}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect

# File upload properties
com.jobportal.image.profile.folder.path=D:\\Project Job Portal\\images\\profile_photo
com.jobportal.image.resume.folder.path=D:\\Project Job Portal\\images\\employee_resume
com.jobportal.image.logo.folder.path=D:\\Project Job Portal\\images\\company_logo

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

springdoc.packagesToScan=com.jobportal.controller
springdoc.pathsToMatch=/api/**

# email smtp setup
spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:ae9ea5001@smtp-brevo.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:Xp4UCgz6AtqnN5dv}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${SPRING_MAIL_HOST:smtp-relay.brevo.com}